In [5]:
import pandas as pd
import numpy as np

# method 1
df = pd.DataFrame([28, 42, 27, 24, 35, 54, 35, 37],columns = ['age'])
print(df)
# method 2
df = pd.DataFrame()
# Populate it with data.
df['age'] = [28, 42, 27, 24, 35, 54, 35, 37]
print(df)

   age
0   28
1   42
2   27
3   24
4   35
5   54
6   35
7   37
   age
0   28
1   42
2   27
3   24
4   35
5   54
6   35
7   37


In [6]:
mean = sum(df['age']) / len(df['age'])
print("mean = "  , mean)

mean =  35.25


In [7]:
# make all values same and calculate mean
df['same'] = (50 - df['age']) + df['age'] 
mean = sum(df['same']) / len(df['same'])
print("mean (same) = "  , mean)

mean (same) =  50.0


In [19]:
import statistics
# using statistics module
print(statistics.median(df['age']))
# using numpy module
print(np.median(df['age']))

35.0
35.0


In [21]:
# trying the mode function
df['other'] = [3,2,3,3,1,1,1,2]
import statistics
print(statistics.mode(df['same']))
#print(statistics.mode(df['other']))

50


In [10]:
import collections
collections.Counter(df['age'])

Counter({28: 1, 42: 1, 27: 1, 24: 1, 35: 2, 54: 1, 37: 1})

In [12]:
# return all unique elements, we can use python set function too
counts = np.unique(df['age'])
print(counts)
# returns unique elements and counts in a tuple
# we can unpack into two numpy arrays
values, counts = np.unique(df['age'], return_counts=True)
print(values, counts)

[24 27 28 35 37 42 54]
[24 27 28 35 37 42 54] [1 1 1 2 1 1 1]


In [27]:
# see how where works
x = np.arange(3)
# the argument inside is like saying an element greater than 1 in x
np.argwhere(x>1)

array([[2]], dtype=int64)

In [43]:
# to return all occurences of the mode
# method 1
print("data\n", df['other'])
values, counts = np.unique(df['other'], return_counts=True)
print("values\n" , values)
print("counts\n" , counts)
the_mode = np.argwhere(counts == np.max(counts))
print("indices of the mode: ", the_mode)
print("mode(s): " , values[the_mode].flatten())


data
 0    3
1    2
2    3
3    3
4    1
5    1
6    1
7    2
Name: other, dtype: int64
values
 [1 2 3]
counts
 [3 2 3]
indices of the mode:  [[0]
 [2]]
mode(s):  [1 3]
