In [8]:
from collections import defaultdict
# default value of int is 0 with defaultdict
continent_dict = defaultdict(int) 

In [9]:
continent_dict

defaultdict(int, {})

In [11]:
continent_dict["tinsae"] = 2.5

In [12]:
continent_dict

defaultdict(int, {'tinsae': 2.5})

In [34]:
import numpy as np
from scipy.sparse import coo_matrix, vstack
m = coo_matrix(np.array([0,0,1,3]))
a = np.array([4,5,6,0])
m = vstack((m, a))

TypeError: __init__() missing 1 required positional argument: 'arg1'

In [32]:
print(m)

  (0, 2)	1
  (0, 3)	3
  (1, 0)	4
  (1, 1)	5
  (1, 2)	6


In [12]:
np.unique([1,2,3,1], return_index=True)

(array([1, 2, 3]), array([0, 1, 2], dtype=int64))

In [33]:
m.toarray()

array([[0, 0, 1, 3],
       [4, 5, 6, 0]], dtype=int32)

In [18]:
import pandas as pd
s = pd.Series([1,2,3,3,2])

d = s.groupby(s).groups
list(d[1])

[0]

In [21]:
saa = np.array([1,2,3,4])
np.insert(saa,0,5)

array([5, 1, 2, 3, 4])